### ISSUE TITLE
[Bug] Context Menus crashing Timezones

### ISSUE THREAD

**Issue by JimMcBubbles** [TheCommieAxolotl/BetterDiscord-Stuff#32]
### Addon

Timezones version 1.0.0

### What happened?

Crashed on right click trying to access vc user-context menu.
![image](https://user-images.githubusercontent.com/60635912/221958043-4ae3885e-75b0-4eee-bdb4-9ba74aa90eb7.png)
div class="menu-2TXYjN flexible-3B4jwn" role="menu" id="user-context" tabindex="-1" aria-label="User Settings Actions"

### What Discord version do you have this issue on?

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by misterpyrrhuloxia** [comment]
I'm having the exact same issue but it's also crashing for me any time I try to right-click on a user in the DM list. Right-clicking on a group DM doesn't have any issues.

**Comment by aaronliu0130** [comment]
Also happens when I right click a profile from a sent-out message.
<details>
	<summary>Relevant logs (I think)</summary>
	<pre>
[2023-02-28 22:05:06.806][CONSOLE:ERROR] Menu API only allows Items and groups of Items as children. Received [object Object] (object) instead
Error: Menu API only allows Items and groups of Items as children. Received [object Object] (object) instead
    at https://discord.com/assets/288aa17d3bf2f0a3351d.js:2748:199
    at Array.reduce (<anonymous>)
    at qr (https://discord.com/assets/288aa17d3bf2f0a3351d.js:2747:14)
    at Jr (https://discord.com/assets/288aa17d3bf2f0a3351d.js:2750:940)
    at <anonymous>:4:31691
    at Sa (https://discord.com/assets/288aa17d3bf2f0a3351d.js:1608:54)
    at yu (https://discord.com/assets/288aa17d3bf2f0a3351d.js:1662:146)
    at Oc (https://discord.com/assets/288aa17d3bf2f0a3351d.js:1655:89)
    at Ic (https://discord.com/assets/288aa17d3bf2f0a3351d.js:1655:17)
    at hc (https://discord.com/assets/288aa17d3bf2f0a3351d.js:1654:867)
    at ic (https://discord.com/assets/288aa17d3bf2f0a3351d.js:1651:642)
    at oc (https://discord.com/assets/288aa17d3bf2f0a3351d.js:1650:184)
    at g (https://discord.com/assets/288aa17d3bf2f0a3351d.js:1772:904)
    at L (https://discord.com/assets/288aa17d3bf2f0a3351d.js:1773:267)
    at t.exports (https://discord.com/assets/ff334c0250254fc1c9ca.js:21:454)
    at g.<computed> (https://discord.com/assets/ff334c0250254fc1c9ca.js:36:394)
    at Number.m (https://discord.com/assets/ff334c0250254fc1c9ca.js:36:255)
    at MessagePort.b (https://discord.com/assets/ff334c0250254fc1c9ca.js:36:277)
[2023-02-28 22:05:08.061][CONSOLE:WARN] Window state not initialized window-1
</pre>
</details>

**Comment by JimMcBubbles** [comment]
![image](https://user-images.githubusercontent.com/60635912/222291314-3fb05e1d-1293-4170-93b7-6ccfa4fe76c5.png)

**Comment by JimMcBubbles** [comment]
bd update means it no longer crashes but context menu doesnt work

**Comment by kvltkt** [comment]
Happening for me if I just open a DM where I already have a timezone applied after update.
