### ISSUE TITLE
[Bug] Timezones edit (server) profile crashes discord

### ISSUE THREAD

**Issue by Miniontoby** [TheCommieAxolotl/BetterDiscord-Stuff#45]
### Addon

Timezones

### What happened?

Discord crashed (with the "OOPS" screen) when I try to edit my (server) profile

### What Discord version do you have this issue on?

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MichaelDavidGK** [comment]
Check other plugins, it doesn't crash with this plugin
also try to go into profiles thru settings
ctrl+shift+i for console and errors (logs)
it will show plugin name or file name of plugin that crashed in error msg

**Comment by Miniontoby** [comment]
When we disable THIS plugin, we can access the (server) profile page.

When looking into the dev logs this is the only thing that is a warning and that showed up during/after the crash:
```js
TypeError: Cannot read properties of undefined (reading 'css')
    at l (3ffb2a2fe2c3a8b21d01.js:5385:90)
    at $i (154605892973cf26a001.js:199:815)
    at Sa (3ffb2a2fe2c3a8b21d01.js:1779:54)
    at gu (3ffb2a2fe2c3a8b21d01.js:1833:146)
    at Ic (3ffb2a2fe2c3a8b21d01.js:1826:89)
    at mc (3ffb2a2fe2c3a8b21d01.js:1826:17)
    at hc (3ffb2a2fe2c3a8b21d01.js:1825:867)
    at oc (3ffb2a2fe2c3a8b21d01.js:1822:642)
    at uc (3ffb2a2fe2c3a8b21d01.js:1823:49)
    at Fi (3ffb2a2fe2c3a8b21d01.js:1762:577)
    at 3ffb2a2fe2c3a8b21d01.js:1820:555
```

P.s. I have used `(server) profile` in my messages, because when we go to the server profile editor AND/OR to the profile editor, discord crashes!
