### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Ade2310** [TheCommieAxolotl/BetterDiscord-Stuff#68]
### Addon

Timexones

### What happened?

Could not be compiled.
<img width="617" alt="image" src="https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/assets/45678636/1721b9cd-2476-49ff-a28e-9ff1ec81b0b5">

### What Discord version do you have this issue on?

PTB

### Logs

```shell
TypeError: Cannot read properties of undefined (reading 'Z')
    at plugin (betterdiscord://plugins/Timezones.plugin.js:137:101)
    at eval (betterdiscord://plugins/Timezones.plugin.js:341:22)
    at eval (betterdiscord://plugins/Timezones.plugin.js:342:13)
    at eval (betterdiscord://plugins/Timezones.plugin.js:343:3)
    at D.requireAddon (betterdiscord/renderer.js:5:33852)
    at D.loadAddon (betterdiscord/renderer.js:5:6322)
    at D.loadAddon (betterdiscord/renderer.js:5:31520)
    at D.reloadAddon (betterdiscord/renderer.js:5:7212)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:5:4336)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
(there is already a pull request open to fix this plugin)
