### ISSUE TITLE
[Bug] "Show local timestamp next to message" doesn't work in PTB

### ISSUE THREAD

**Issue by Lusiiky** [TheCommieAxolotl/BetterDiscord-Stuff#85]
### Addon

Timezones

### What happened?

The time with the user's timezone when he sent the message doesn't appear when "*Show local timestamp next to message*" is enabled, on PTB only.

### What Discord version do you have this issue on?

PTB
*(I haven't personally tested it on Canary, but I assume that the problem is also present(?))*

### Logs

Error appearing in the console, on PTB, when loading messages with a user who has a timezone set - appears several times:
```
VM405 47470.91c2d89ebc10ef7a8bdd.js:1 [BetterDiscord] [Patcher] Could not fire after callback of default for Timezones RangeError: Invalid time value
    at Timezones.getTime (Timezones.plugin.js:302:44)
    at Object.eval [as callback] (Timezones.plugin.js:176:50)
    at renderer.js:5:28288
    at ob (25979.ba7e12ad3432f0dc414b.js:1:808076)
    at ih (25979.ba7e12ad3432f0dc414b.js:1:819970)
    at u (25979.ba7e12ad3432f0dc414b.js:1:864183)
    at sN (25979.ba7e12ad3432f0dc414b.js:1:846302)
    at 25979.ba7e12ad3432f0dc414b.js:1:846168
    at sI (25979.ba7e12ad3432f0dc414b.js:1:846176)
    at sx (25979.ba7e12ad3432f0dc414b.js:1:843261)
    at r6 (25979.ba7e12ad3432f0dc414b.js:1:791951)
    at 25979.ba7e12ad3432f0dc414b.js:1:840799
(anonymous) @ VM405 47470.91c2d89ebc10ef7a8bdd.js:1
_log @ renderer.js:5
err @ renderer.js:5
(anonymous) @ renderer.js:5
ob @ 25979.ba7e12ad3432f0dc414b.js:1
ih @ 25979.ba7e12ad3432f0dc414b.js:1
u @ 25979.ba7e12ad3432f0dc414b.js:1
sN @ 25979.ba7e12ad3432f0dc414b.js:1
(anonymous) @ 25979.ba7e12ad3432f0dc414b.js:1
sI @ 25979.ba7e12ad3432f0dc414b.js:1
sx @ 25979.ba7e12ad3432f0dc414b.js:1
r6 @ 25979.ba7e12ad3432f0dc414b.js:1
(anonymous) @ 25979.ba7e12ad3432f0dc414b.js:1
```

![image](https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/assets/29005043/4b0baac9-89bf-4622-adba-f1d267cf9981)

### Code of Conduct
```
- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
Can you please test with the latest commit

**Comment by Lusiiky** [comment]
> Can you please test with the latest commit

It work now, thank you!
