### ISSUE TITLE
Timezones Could not be compiled [Bug] 

### ISSUE THREAD

**Issue by TheGreatTaz** [TheCommieAxolotl/BetterDiscord-Stuff#95]
### Addon

Timezones

### What happened?

An error was encountered while trying to load this plugin.

### What Discord version do you have this issue on?

Stable

### Logs

```shell
TypeError: Cannot read properties of undefined (reading 'default')
    at plugin (betterdiscord://plugins/Timezones.plugin.js:143:113)
    at eval (betterdiscord://plugins/Timezones.plugin.js:313:22)
    at eval (betterdiscord://plugins/Timezones.plugin.js:314:13)
    at eval (betterdiscord://plugins/Timezones.plugin.js:315:3)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by minnieoo** [comment]
same happening here!

**Comment by Allydoodle2187** [comment]
Same thing for me

**Comment by ROMAiev** [comment]
Same

**Comment by alez54** [comment]
same

**Comment by StripedPuppy** [comment]
Same for this doggo.

**Comment by Manos654764** [comment]
same. +1

**Comment by Zhurama** [comment]
Happening here as well +1

**Comment by arfans22** [comment]
same here

**Comment by LabRatMime** [comment]
yeahh me too 😔

**Comment by TheRealKn1ghtSp1der** [comment]
same here too

**Comment by Minecraft-Gamer-Nation** [comment]
same here lmao

**Comment by aeholic** [comment]
Same

**Comment by WlSDXM** [comment]
is an update being worked on?

**Comment by StripedPuppy** [comment]
@TheCommieAxolotl

**Comment by CoboltWings** [comment]
Just chiming in but having issues as well.

**Comment by TheCommieAxolotl** [comment]
Fixed in https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/commit/7fe997c2105bf265500fc6cf56e0bcaab504e7bf
