### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by treatmeniceplz** [TheCommieAxolotl/BetterDiscord-Stuff#96]
### Addon

Timezones

### What happened?

failed to compile

### What Discord version do you have this issue on?

Stable

### Logs

```shell
TypeError: Cannot read properties of undefined (reading 'default')
    at plugin (betterdiscord://plugins/Timezones.plugin.js:143:113)
    at eval (betterdiscord://plugins/Timezones.plugin.js:313:22)
    at eval (betterdiscord://plugins/Timezones.plugin.js:314:13)
    at eval (betterdiscord://plugins/Timezones.plugin.js:315:3)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by treatmeniceplz** [comment]
I also see that in the settings

**Comment by treatmeniceplz** [comment]
The WHAT

**Comment by treatmeniceplz** [comment]
@TheCommieAxolotl This is not completed

**Comment by treatmeniceplz** [comment]
What is the solution

**Comment by TheCommieAxolotl** [comment]
Download the latest version, this has been fixed.

**Comment by TheCommieAxolotl** [comment]
https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/commit/7fe997c2105bf265500fc6cf56e0bcaab504e7bf
